# LLM 
API_KEY_LLM = "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"
MODEL_ID_LLM = "openai/gpt-4.1-nano"

# TMDB
TMDB_API_KEY = "36caa20fe809483164b091f69446b7da"

# Database
database_url = "sqlite:///./movieagent.db"

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "2b6f8d9c1e4a7f53c8a1d2e9b4f6a7c1d8e3f5a9b2c4d6e8f1a3b5c7d9e2f4a"

[auth.auth0]
domain = "movieagentos.eu.auth0.com"
client_id = "tQtlrDu5hVi0Q30wuq5fn4Wvj7WCGIeR"
client_secret = "d7Lq_L2xeqQWPu6voV98AUqnQk-I1atWuubCIXVci_612Jz0TmoWQJKlQ5O36WFT"
server_metadata_url = "https://movieagentos.eu.auth0.com/.well-known/openid-configuration"
client_kwargs = {"prompt" = "login"}

[browser]
gatherUsageStats = false
